server:
  port: 8081
spring:
  application:
    name: mall-order  #微服务名称

  #配置nacos注册中心地址
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
        # 对应在Nacos中创建的命名空间
#        namespace: 7080361d-8b1b-4bfd-a6c4-38125b2906dc
#        group: tuling-ylb

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
